// Code generated by MockGen. DO NOT EDIT.
// Source: org_user.go
//
// Generated by this command:
//
//	mockgen -source=org_user.go -destination=mock/org_user_test.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/vtuanjs/saas_management/apps/saas_mngt_service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOrgUserRepository is a mock of OrgUserRepository interface.
type MockOrgUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrgUserRepositoryMockRecorder
	isgomock struct{}
}

// MockOrgUserRepositoryMockRecorder is the mock recorder for MockOrgUserRepository.
type MockOrgUserRepositoryMockRecorder struct {
	mock *MockOrgUserRepository
}

// NewMockOrgUserRepository creates a new mock instance.
func NewMockOrgUserRepository(ctrl *gomock.Controller) *MockOrgUserRepository {
	mock := &MockOrgUserRepository{ctrl: ctrl}
	mock.recorder = &MockOrgUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrgUserRepository) EXPECT() *MockOrgUserRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockOrgUserRepository) FindByID(ctx context.Context, id string) (*entity.OrgUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.OrgUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockOrgUserRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockOrgUserRepository)(nil).FindByID), ctx, id)
}

// Save mocks base method.
func (m *MockOrgUserRepository) Save(ctx context.Context, orgUser *entity.OrgUser) (*entity.OrgUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, orgUser)
	ret0, _ := ret[0].(*entity.OrgUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockOrgUserRepositoryMockRecorder) Save(ctx, orgUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockOrgUserRepository)(nil).Save), ctx, orgUser)
}
