version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    misspell:
      locale: US
      ignore-rules:
        - studdy
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # disable unused linter for packages in features directory,
      # because those are invoked by godog, that makes the
      # unused linter reports false positive errors.
      - linters:
          - goconst
          - unused
        path: features
      - linters:
          - goconst
        path: cmd
    paths:
      - ^mock/
      - ^pkg/
      - third_party$
      - builtin$
      - examples$
      - ent

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - prefix(github.com/vtuanjs/saas_management)
        - default
      custom-order: true
    golines:
      max-len: 120
      tab-len: 1
  exclusions:
    generated: lax
    paths:
      - ^mock/
      - ^pkg/
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 50
  max-same-issues: 0

run:
  timeout: 20m
  tests: false
  modules-download-mode: readonly
