// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/infrastructures/postgres/sqlc/querier.go
//
// Generated by this command:
//
//	mockgen -source=./internal/infrastructures/postgres/sqlc/querier.go -destination=./internal/infrastructures/postgres/sqlc/mock/querier_test.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/vtuanjs/saas_management/apps/saas_mngt_service/internal/infrastructures/postgres/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// GetOrganizationByID mocks base method.
func (m *MockQuerier) GetOrganizationByID(ctx context.Context, id string) (*sqlc.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationByID", ctx, id)
	ret0, _ := ret[0].(*sqlc.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationByID indicates an expected call of GetOrganizationByID.
func (mr *MockQuerierMockRecorder) GetOrganizationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationByID", reflect.TypeOf((*MockQuerier)(nil).GetOrganizationByID), ctx, id)
}

// GetOrganizationMembershipByID mocks base method.
func (m *MockQuerier) GetOrganizationMembershipByID(ctx context.Context, id string) (*sqlc.OrganizationMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationMembershipByID", ctx, id)
	ret0, _ := ret[0].(*sqlc.OrganizationMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationMembershipByID indicates an expected call of GetOrganizationMembershipByID.
func (mr *MockQuerierMockRecorder) GetOrganizationMembershipByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationMembershipByID", reflect.TypeOf((*MockQuerier)(nil).GetOrganizationMembershipByID), ctx, id)
}

// GetPermissionByID mocks base method.
func (m *MockQuerier) GetPermissionByID(ctx context.Context, id string) (*sqlc.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionByID", ctx, id)
	ret0, _ := ret[0].(*sqlc.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionByID indicates an expected call of GetPermissionByID.
func (mr *MockQuerierMockRecorder) GetPermissionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionByID", reflect.TypeOf((*MockQuerier)(nil).GetPermissionByID), ctx, id)
}

// GetRefreshTokenByID mocks base method.
func (m *MockQuerier) GetRefreshTokenByID(ctx context.Context, id string) (*sqlc.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenByID", ctx, id)
	ret0, _ := ret[0].(*sqlc.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenByID indicates an expected call of GetRefreshTokenByID.
func (mr *MockQuerierMockRecorder) GetRefreshTokenByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenByID", reflect.TypeOf((*MockQuerier)(nil).GetRefreshTokenByID), ctx, id)
}

// GetRoleByID mocks base method.
func (m *MockQuerier) GetRoleByID(ctx context.Context, id string) (*sqlc.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByID", ctx, id)
	ret0, _ := ret[0].(*sqlc.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByID indicates an expected call of GetRoleByID.
func (mr *MockQuerierMockRecorder) GetRoleByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByID", reflect.TypeOf((*MockQuerier)(nil).GetRoleByID), ctx, id)
}

// GetRolePermissionByID mocks base method.
func (m *MockQuerier) GetRolePermissionByID(ctx context.Context, id string) (*sqlc.RolePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolePermissionByID", ctx, id)
	ret0, _ := ret[0].(*sqlc.RolePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolePermissionByID indicates an expected call of GetRolePermissionByID.
func (mr *MockQuerierMockRecorder) GetRolePermissionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolePermissionByID", reflect.TypeOf((*MockQuerier)(nil).GetRolePermissionByID), ctx, id)
}

// GetUserByID mocks base method.
func (m *MockQuerier) GetUserByID(ctx context.Context, id string) (*sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockQuerierMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockQuerier)(nil).GetUserByID), ctx, id)
}

// SaveOrganization mocks base method.
func (m *MockQuerier) SaveOrganization(ctx context.Context, arg sqlc.SaveOrganizationParams) (*sqlc.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrganization", ctx, arg)
	ret0, _ := ret[0].(*sqlc.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveOrganization indicates an expected call of SaveOrganization.
func (mr *MockQuerierMockRecorder) SaveOrganization(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrganization", reflect.TypeOf((*MockQuerier)(nil).SaveOrganization), ctx, arg)
}

// SaveOrganizationMembership mocks base method.
func (m *MockQuerier) SaveOrganizationMembership(ctx context.Context, arg sqlc.SaveOrganizationMembershipParams) (*sqlc.OrganizationMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrganizationMembership", ctx, arg)
	ret0, _ := ret[0].(*sqlc.OrganizationMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveOrganizationMembership indicates an expected call of SaveOrganizationMembership.
func (mr *MockQuerierMockRecorder) SaveOrganizationMembership(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrganizationMembership", reflect.TypeOf((*MockQuerier)(nil).SaveOrganizationMembership), ctx, arg)
}

// SavePermission mocks base method.
func (m *MockQuerier) SavePermission(ctx context.Context, arg sqlc.SavePermissionParams) (*sqlc.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePermission", ctx, arg)
	ret0, _ := ret[0].(*sqlc.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SavePermission indicates an expected call of SavePermission.
func (mr *MockQuerierMockRecorder) SavePermission(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePermission", reflect.TypeOf((*MockQuerier)(nil).SavePermission), ctx, arg)
}

// SaveRefreshToken mocks base method.
func (m *MockQuerier) SaveRefreshToken(ctx context.Context, arg sqlc.SaveRefreshTokenParams) (*sqlc.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRefreshToken", ctx, arg)
	ret0, _ := ret[0].(*sqlc.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveRefreshToken indicates an expected call of SaveRefreshToken.
func (mr *MockQuerierMockRecorder) SaveRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRefreshToken", reflect.TypeOf((*MockQuerier)(nil).SaveRefreshToken), ctx, arg)
}

// SaveRole mocks base method.
func (m *MockQuerier) SaveRole(ctx context.Context, arg sqlc.SaveRoleParams) (*sqlc.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRole", ctx, arg)
	ret0, _ := ret[0].(*sqlc.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveRole indicates an expected call of SaveRole.
func (mr *MockQuerierMockRecorder) SaveRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRole", reflect.TypeOf((*MockQuerier)(nil).SaveRole), ctx, arg)
}

// SaveRolePermission mocks base method.
func (m *MockQuerier) SaveRolePermission(ctx context.Context, arg sqlc.SaveRolePermissionParams) (*sqlc.RolePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRolePermission", ctx, arg)
	ret0, _ := ret[0].(*sqlc.RolePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveRolePermission indicates an expected call of SaveRolePermission.
func (mr *MockQuerierMockRecorder) SaveRolePermission(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRolePermission", reflect.TypeOf((*MockQuerier)(nil).SaveRolePermission), ctx, arg)
}

// SaveUser mocks base method.
func (m *MockQuerier) SaveUser(ctx context.Context, arg sqlc.SaveUserParams) (*sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", ctx, arg)
	ret0, _ := ret[0].(*sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockQuerierMockRecorder) SaveUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockQuerier)(nil).SaveUser), ctx, arg)
}
