// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/vtuanjs/saas_management/apps/saas_mngt_service/internal/core"
	"github.com/vtuanjs/saas_management/apps/saas_mngt_service/libs/redis"
	"github.com/vtuanjs/saas_management/apps/saas_mngt_service/libs/viper"
	"github.com/vtuanjs/saas_management/apps/saas_mngt_service/libs/zap"
)

// Injectors from wire.go:

func InitConfig() *core.Config {
	config := viper.NewConfig()
	return config
}

func InitLogger() core.Logger {
	config := viper.NewConfig()
	logger := zap.NewLogger(config)
	return logger
}

func InitDistributedCache() core.Cache {
	config := viper.NewConfig()
	cache := redis.NewRedisCache(config)
	return cache
}
