// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type Organization struct {
	ID          string
	Code        string
	Name        string
	Logo        []byte
	IsLocked    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	UpdatedByID *string
	DeletedAt   *time.Time
	Version     int32
}

type OrganizationMembership struct {
	ID          string
	UserID      string
	OrgID       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	UpdatedByID *string
	DeletedAt   *time.Time
	Version     int32
}

type Permission struct {
	ID          string
	Name        string
	Description string
	System      bool
	OrgID       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	UpdatedByID *string
	DeletedAt   *time.Time
	Version     int32
}

type RefreshToken struct {
	ID        string
	TokenID   string
	ExpiresAt *time.Time
	Device    []byte
	Ip        string
	UserID    string
	CreatedAt time.Time
	UpdatedAt time.Time
	Version   int32
}

type Role struct {
	ID          string
	Name        string
	Description string
	System      bool
	OrgID       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	UpdatedByID *string
	DeletedAt   *time.Time
	Version     int32
}

type RolePermission struct {
	ID           string
	UserID       string
	RoleID       string
	PermissionID string
	OrgID        string
	Resources    []string
	CreatedAt    time.Time
	CreatedByID  *string
}

type User struct {
	ID                   string
	Email                string
	Phone                string
	FirstName            string
	LastName             string
	Name                 *string
	Avatar               []byte
	LastLogin            *time.Time
	Ref                  *string
	IsLocked             bool
	IsActivated          bool
	IsAdmin              bool
	IsChangePassRequired bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CreatedByID          *string
	UpdatedByID          *string
	DeletedAt            *time.Time
	Version              int32
}
