// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type User struct {
	ID                   string
	Email                string
	Phone                string
	FirstName            string
	LastName             string
	Name                 string
	AvatarID             *string
	LastLogin            *time.Time
	RefID                *string
	IsLocked             bool
	IsActivated          bool
	IsAdmin              bool
	IsChangePassRequired bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CreatedByID          *string
	UpdatedByID          *string
	DeletedAt            *time.Time
	Version              int32
}
