// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: org_user.sql

package sqlc

import (
	"context"
	"time"
)

const getOrgUserByID = `-- name: GetOrgUserByID :one
SELECT id, user_id, org_id, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version FROM org_users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrgUserByID(ctx context.Context, id string) (*OrgUser, error) {
	row := q.db.QueryRow(ctx, getOrgUserByID, id)
	var i OrgUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}

const saveOrgUser = `-- name: SaveOrgUser :one
INSERT INTO org_users (
    id,
    user_id,
    org_id,
    created_at,
    updated_at,
    created_by_id,
    updated_by_id,
    deleted_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (id) DO UPDATE
SET
    user_id = EXCLUDED.user_id,
    org_id = EXCLUDED.org_id,
    updated_at = EXCLUDED.updated_at,
    updated_by_id = EXCLUDED.updated_by_id,
    deleted_at = EXCLUDED.deleted_at,
    version = org_users.version + 1
RETURNING id, user_id, org_id, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version
`

type SaveOrgUserParams struct {
	ID          string
	UserID      string
	OrgID       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	UpdatedByID *string
	DeletedAt   *time.Time
}

func (q *Queries) SaveOrgUser(ctx context.Context, arg SaveOrgUserParams) (*OrgUser, error) {
	row := q.db.QueryRow(ctx, saveOrgUser,
		arg.ID,
		arg.UserID,
		arg.OrgID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedByID,
		arg.UpdatedByID,
		arg.DeletedAt,
	)
	var i OrgUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}
