// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: org_sync_template.sql

package sqlc

import (
	"context"
	"time"
)

const getOrgSyncTemplateByID = `-- name: GetOrgSyncTemplateByID :one
SELECT id, template_name, template_type, template_data, active, created_at, updated_at, version FROM org_sync_templates WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrgSyncTemplateByID(ctx context.Context, id string) (*OrgSyncTemplate, error) {
	row := q.db.QueryRow(ctx, getOrgSyncTemplateByID, id)
	var i OrgSyncTemplate
	err := row.Scan(
		&i.ID,
		&i.TemplateName,
		&i.TemplateType,
		&i.TemplateData,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return &i, err
}

const saveOrgSyncTemplate = `-- name: SaveOrgSyncTemplate :one
INSERT INTO org_sync_templates (
    id,
    template_name,
    template_type,
    template_data,
    active,
    created_at,
    updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id) DO UPDATE
SET
    template_name = EXCLUDED.template_name,
    template_type = EXCLUDED.template_type,
    template_data = EXCLUDED.template_data,
    active = EXCLUDED.active,
    updated_at = EXCLUDED.updated_at,
    version = org_sync_templates.version + 1
RETURNING id, template_name, template_type, template_data, active, created_at, updated_at, version
`

type SaveOrgSyncTemplateParams struct {
	ID           string
	TemplateName string
	TemplateType TemplateType
	TemplateData []byte
	Active       bool
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
}

func (q *Queries) SaveOrgSyncTemplate(ctx context.Context, arg SaveOrgSyncTemplateParams) (*OrgSyncTemplate, error) {
	row := q.db.QueryRow(ctx, saveOrgSyncTemplate,
		arg.ID,
		arg.TemplateName,
		arg.TemplateType,
		arg.TemplateData,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i OrgSyncTemplate
	err := row.Scan(
		&i.ID,
		&i.TemplateName,
		&i.TemplateType,
		&i.TemplateData,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return &i, err
}
