// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: organization.sql

package sqlc

import (
	"context"
	"time"
)

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, code, name, logo, is_locked, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version FROM organizations WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id string) (*Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Logo,
		&i.IsLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}

const saveOrganization = `-- name: SaveOrganization :one
INSERT INTO organizations (
    id,
    code,
    name,
    logo,
    is_locked,
    created_at,
    updated_at,
    created_by_id,
    updated_by_id,
    deleted_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (id) DO UPDATE
SET
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    logo = EXCLUDED.logo,
    is_locked = EXCLUDED.is_locked,
    updated_at = EXCLUDED.updated_at,
    updated_by_id = EXCLUDED.updated_by_id,
    deleted_at = EXCLUDED.deleted_at,
    version = organizations.version + 1
RETURNING id, code, name, logo, is_locked, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version
`

type SaveOrganizationParams struct {
	ID          string
	Code        string
	Name        string
	Logo        []byte
	IsLocked    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	UpdatedByID *string
	DeletedAt   *time.Time
}

func (q *Queries) SaveOrganization(ctx context.Context, arg SaveOrganizationParams) (*Organization, error) {
	row := q.db.QueryRow(ctx, saveOrganization,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Logo,
		arg.IsLocked,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedByID,
		arg.UpdatedByID,
		arg.DeletedAt,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Logo,
		&i.IsLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}
