// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: organization_membership.sql

package sqlc

import (
	"context"
	"time"
)

const getOrganizationMembershipByID = `-- name: GetOrganizationMembershipByID :one
SELECT id, user_id, org_id, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version FROM organization_memberships WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationMembershipByID(ctx context.Context, id string) (*OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getOrganizationMembershipByID, id)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}

const saveOrganizationMembership = `-- name: SaveOrganizationMembership :one
INSERT INTO organization_memberships (
    id,
    user_id,
    org_id,
    created_at,
    updated_at,
    created_by_id,
    updated_by_id,
    deleted_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (id) DO UPDATE
SET
    user_id = EXCLUDED.user_id,
    org_id = EXCLUDED.org_id,
    updated_at = EXCLUDED.updated_at,
    updated_by_id = EXCLUDED.updated_by_id,
    deleted_at = EXCLUDED.deleted_at,
    version = org_users.version + 1
RETURNING id, user_id, org_id, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version
`

type SaveOrganizationMembershipParams struct {
	ID          string
	UserID      string
	OrgID       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	UpdatedByID *string
	DeletedAt   *time.Time
}

func (q *Queries) SaveOrganizationMembership(ctx context.Context, arg SaveOrganizationMembershipParams) (*OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, saveOrganizationMembership,
		arg.ID,
		arg.UserID,
		arg.OrgID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedByID,
		arg.UpdatedByID,
		arg.DeletedAt,
	)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}
