// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: permission.sql

package sqlc

import (
	"context"
	"time"
)

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, code, name, description, system, org_id, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version FROM permissions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPermissionByID(ctx context.Context, id string) (*Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.System,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}

const savePermission = `-- name: SavePermission :one
INSERT INTO permissions (
    id,
    code,
    name,
    description,
    system,
    org_id,
    created_at,
    updated_at,
    created_by_id,
    updated_by_id,
    deleted_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (id) DO UPDATE
SET
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    system = EXCLUDED.system,
    org_id = EXCLUDED.org_id,
    updated_at = EXCLUDED.updated_at,
    updated_by_id = EXCLUDED.updated_by_id,
    deleted_at = EXCLUDED.deleted_at,
    version = permissions.version + 1
RETURNING id, code, name, description, system, org_id, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version
`

type SavePermissionParams struct {
	ID          string
	Code        string
	Name        string
	Description string
	System      bool
	OrgID       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	UpdatedByID *string
	DeletedAt   *time.Time
}

func (q *Queries) SavePermission(ctx context.Context, arg SavePermissionParams) (*Permission, error) {
	row := q.db.QueryRow(ctx, savePermission,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.System,
		arg.OrgID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedByID,
		arg.UpdatedByID,
		arg.DeletedAt,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.System,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}
