// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: project.sql

package sqlc

import (
	"context"
	"time"
)

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, code, parent_id, logo, org_id, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version FROM projects WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (*Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.Logo,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}

const saveProject = `-- name: SaveProject :one
INSERT INTO projects (
    id,
    name,
    code,
    parent_id,
    logo,
    org_id,
    created_at,
    updated_at,
    created_by_id,
    updated_by_id,
    deleted_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    code = EXCLUDED.code,
    parent_id = EXCLUDED.parent_id,
    logo = EXCLUDED.logo,
    org_id = EXCLUDED.org_id,
    updated_at = EXCLUDED.updated_at,
    updated_by_id = EXCLUDED.updated_by_id,
    deleted_at = EXCLUDED.deleted_at,
    version = projects.version + 1
RETURNING id, name, code, parent_id, logo, org_id, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version
`

type SaveProjectParams struct {
	ID          string
	Name        string
	Code        string
	ParentID    *string
	Logo        []byte
	OrgID       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatedByID *string
	UpdatedByID *string
	DeletedAt   *time.Time
}

func (q *Queries) SaveProject(ctx context.Context, arg SaveProjectParams) (*Project, error) {
	row := q.db.QueryRow(ctx, saveProject,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.ParentID,
		arg.Logo,
		arg.OrgID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedByID,
		arg.UpdatedByID,
		arg.DeletedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.ParentID,
		&i.Logo,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}
