// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetUserByID(ctx context.Context, id string) (*User, error)
	SaveUser(ctx context.Context, arg SaveUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
