// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetOrganizationByID(ctx context.Context, id string) (*Organization, error)
	GetOrganizationMembershipByID(ctx context.Context, id string) (*OrganizationMembership, error)
	GetPermissionByID(ctx context.Context, id string) (*Permission, error)
	GetRefreshTokenByID(ctx context.Context, id string) (*RefreshToken, error)
	GetRoleByID(ctx context.Context, id string) (*Role, error)
	GetRolePermissionByID(ctx context.Context, id string) (*RolePermission, error)
	GetUserByID(ctx context.Context, id string) (*User, error)
	SaveOrganization(ctx context.Context, arg SaveOrganizationParams) (*Organization, error)
	SaveOrganizationMembership(ctx context.Context, arg SaveOrganizationMembershipParams) (*OrganizationMembership, error)
	SavePermission(ctx context.Context, arg SavePermissionParams) (*Permission, error)
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) (*RefreshToken, error)
	SaveRole(ctx context.Context, arg SaveRoleParams) (*Role, error)
	SaveRolePermission(ctx context.Context, arg SaveRolePermissionParams) (*RolePermission, error)
	SaveUser(ctx context.Context, arg SaveUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
