// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: role_permission.sql

package sqlc

import (
	"context"
	"time"
)

const getRolePermissionByID = `-- name: GetRolePermissionByID :one
SELECT id, user_id, role_id, permission_id, project_id, org_id, created_at, created_by_id FROM role_permissions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRolePermissionByID(ctx context.Context, id string) (*RolePermission, error) {
	row := q.db.QueryRow(ctx, getRolePermissionByID, id)
	var i RolePermission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.PermissionID,
		&i.ProjectID,
		&i.OrgID,
		&i.CreatedAt,
		&i.CreatedByID,
	)
	return &i, err
}

const saveRolePermission = `-- name: SaveRolePermission :one
INSERT INTO role_permissions (
    id,
    user_id,
    role_id,
    permission_id,
    project_id,
    org_id,
    created_at,
    created_by_id
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (id) DO UPDATE
SET
    user_id = EXCLUDED.user_id,
    role_id = EXCLUDED.role_id,
    permission_id = EXCLUDED.permission_id,
    project_id = EXCLUDED.project_id,
    org_id = EXCLUDED.org_id,
    created_by_id = EXCLUDED.created_by_id
RETURNING id, user_id, role_id, permission_id, project_id, org_id, created_at, created_by_id
`

type SaveRolePermissionParams struct {
	ID           string
	UserID       string
	RoleID       string
	PermissionID string
	ProjectID    string
	OrgID        string
	CreatedAt    time.Time
	CreatedByID  *string
}

func (q *Queries) SaveRolePermission(ctx context.Context, arg SaveRolePermissionParams) (*RolePermission, error) {
	row := q.db.QueryRow(ctx, saveRolePermission,
		arg.ID,
		arg.UserID,
		arg.RoleID,
		arg.PermissionID,
		arg.ProjectID,
		arg.OrgID,
		arg.CreatedAt,
		arg.CreatedByID,
	)
	var i RolePermission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.PermissionID,
		&i.ProjectID,
		&i.OrgID,
		&i.CreatedAt,
		&i.CreatedByID,
	)
	return &i, err
}
