// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package sqlc

import (
	"context"
	"time"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, first_name, last_name, name, avatar, last_login, ref, is_locked, is_activated, is_admin, is_change_pass_required, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.Name,
		&i.Avatar,
		&i.LastLogin,
		&i.Ref,
		&i.IsLocked,
		&i.IsActivated,
		&i.IsAdmin,
		&i.IsChangePassRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}

const saveUser = `-- name: SaveUser :one
INSERT INTO users (
    id,
    email,
    phone,
    first_name,
    last_name,
    avatar,
    last_login,
    ref,
    is_locked,
    is_activated,
    is_change_pass_required,
    created_at,
    updated_at,
    created_by_id,
    updated_by_id,
    deleted_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (id) DO UPDATE
SET
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    avatar = EXCLUDED.avatar,
    last_login = EXCLUDED.last_login,
    ref = EXCLUDED.ref,
    is_locked = EXCLUDED.is_locked,
    is_activated = EXCLUDED.is_activated,
    is_change_pass_required = EXCLUDED.is_change_pass_required,
    updated_at = EXCLUDED.updated_at,
    updated_by_id = EXCLUDED.updated_by_id,
    deleted_at = EXCLUDED.deleted_at,
    version = users.version + 1
RETURNING id, email, phone, first_name, last_name, name, avatar, last_login, ref, is_locked, is_activated, is_admin, is_change_pass_required, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version
`

type SaveUserParams struct {
	ID                   string
	Email                string
	Phone                string
	FirstName            string
	LastName             string
	Avatar               []byte
	LastLogin            *time.Time
	Ref                  *string
	IsLocked             bool
	IsActivated          bool
	IsChangePassRequired bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CreatedByID          *string
	UpdatedByID          *string
	DeletedAt            *time.Time
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, saveUser,
		arg.ID,
		arg.Email,
		arg.Phone,
		arg.FirstName,
		arg.LastName,
		arg.Avatar,
		arg.LastLogin,
		arg.Ref,
		arg.IsLocked,
		arg.IsActivated,
		arg.IsChangePassRequired,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CreatedByID,
		arg.UpdatedByID,
		arg.DeletedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.Name,
		&i.Avatar,
		&i.LastLogin,
		&i.Ref,
		&i.IsLocked,
		&i.IsActivated,
		&i.IsAdmin,
		&i.IsChangePassRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}
