// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
RETURNING id, email, phone, first_name, last_name, name, avatar_id, last_login, ref_id, is_locked, is_activated, is_admin, is_change_pass_required, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version
`

type CreateUserParams struct {
	Name  string
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.Name,
		&i.AvatarID,
		&i.LastLogin,
		&i.RefID,
		&i.IsLocked,
		&i.IsActivated,
		&i.IsAdmin,
		&i.IsChangePassRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, first_name, last_name, name, avatar_id, last_login, ref_id, is_locked, is_activated, is_admin, is_change_pass_required, created_at, updated_at, created_by_id, updated_by_id, deleted_at, version FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.Name,
		&i.AvatarID,
		&i.LastLogin,
		&i.RefID,
		&i.IsLocked,
		&i.IsActivated,
		&i.IsAdmin,
		&i.IsChangePassRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByID,
		&i.UpdatedByID,
		&i.DeletedAt,
		&i.Version,
	)
	return &i, err
}
