// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: saas/v1/auth.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/vtuanjs/saas_management/packages/go/buf/saas/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthAPIName is the fully-qualified name of the AuthAPI service.
	AuthAPIName = "saas.v1.AuthAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthAPILoginWithEmailProcedure is the fully-qualified name of the AuthAPI's LoginWithEmail RPC.
	AuthAPILoginWithEmailProcedure = "/saas.v1.AuthAPI/LoginWithEmail"
	// AuthAPILoginWithCodeProcedure is the fully-qualified name of the AuthAPI's LoginWithCode RPC.
	AuthAPILoginWithCodeProcedure = "/saas.v1.AuthAPI/LoginWithCode"
	// AuthAPILogoutProcedure is the fully-qualified name of the AuthAPI's Logout RPC.
	AuthAPILogoutProcedure = "/saas.v1.AuthAPI/Logout"
	// AuthAPIRefreshTokenProcedure is the fully-qualified name of the AuthAPI's RefreshToken RPC.
	AuthAPIRefreshTokenProcedure = "/saas.v1.AuthAPI/RefreshToken"
)

// AuthAPIClient is a client for the saas.v1.AuthAPI service.
type AuthAPIClient interface {
	LoginWithEmail(context.Context, *connect.Request[v1.LoginWithEmailRequest]) (*connect.Response[v1.LoginWithEmailResponse], error)
	LoginWithCode(context.Context, *connect.Request[v1.LoginWithCodeRequest]) (*connect.Response[v1.LoginWithCodeResponse], error)
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
	RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error)
}

// NewAuthAPIClient constructs a client for the saas.v1.AuthAPI service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authAPIMethods := v1.File_saas_v1_auth_proto.Services().ByName("AuthAPI").Methods()
	return &authAPIClient{
		loginWithEmail: connect.NewClient[v1.LoginWithEmailRequest, v1.LoginWithEmailResponse](
			httpClient,
			baseURL+AuthAPILoginWithEmailProcedure,
			connect.WithSchema(authAPIMethods.ByName("LoginWithEmail")),
			connect.WithClientOptions(opts...),
		),
		loginWithCode: connect.NewClient[v1.LoginWithCodeRequest, v1.LoginWithCodeResponse](
			httpClient,
			baseURL+AuthAPILoginWithCodeProcedure,
			connect.WithSchema(authAPIMethods.ByName("LoginWithCode")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[v1.LogoutRequest, v1.LogoutResponse](
			httpClient,
			baseURL+AuthAPILogoutProcedure,
			connect.WithSchema(authAPIMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
		refreshToken: connect.NewClient[v1.RefreshTokenRequest, v1.RefreshTokenResponse](
			httpClient,
			baseURL+AuthAPIRefreshTokenProcedure,
			connect.WithSchema(authAPIMethods.ByName("RefreshToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authAPIClient implements AuthAPIClient.
type authAPIClient struct {
	loginWithEmail *connect.Client[v1.LoginWithEmailRequest, v1.LoginWithEmailResponse]
	loginWithCode  *connect.Client[v1.LoginWithCodeRequest, v1.LoginWithCodeResponse]
	logout         *connect.Client[v1.LogoutRequest, v1.LogoutResponse]
	refreshToken   *connect.Client[v1.RefreshTokenRequest, v1.RefreshTokenResponse]
}

// LoginWithEmail calls saas.v1.AuthAPI.LoginWithEmail.
func (c *authAPIClient) LoginWithEmail(ctx context.Context, req *connect.Request[v1.LoginWithEmailRequest]) (*connect.Response[v1.LoginWithEmailResponse], error) {
	return c.loginWithEmail.CallUnary(ctx, req)
}

// LoginWithCode calls saas.v1.AuthAPI.LoginWithCode.
func (c *authAPIClient) LoginWithCode(ctx context.Context, req *connect.Request[v1.LoginWithCodeRequest]) (*connect.Response[v1.LoginWithCodeResponse], error) {
	return c.loginWithCode.CallUnary(ctx, req)
}

// Logout calls saas.v1.AuthAPI.Logout.
func (c *authAPIClient) Logout(ctx context.Context, req *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// RefreshToken calls saas.v1.AuthAPI.RefreshToken.
func (c *authAPIClient) RefreshToken(ctx context.Context, req *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error) {
	return c.refreshToken.CallUnary(ctx, req)
}

// AuthAPIHandler is an implementation of the saas.v1.AuthAPI service.
type AuthAPIHandler interface {
	LoginWithEmail(context.Context, *connect.Request[v1.LoginWithEmailRequest]) (*connect.Response[v1.LoginWithEmailResponse], error)
	LoginWithCode(context.Context, *connect.Request[v1.LoginWithCodeRequest]) (*connect.Response[v1.LoginWithCodeResponse], error)
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
	RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error)
}

// NewAuthAPIHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthAPIHandler(svc AuthAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authAPIMethods := v1.File_saas_v1_auth_proto.Services().ByName("AuthAPI").Methods()
	authAPILoginWithEmailHandler := connect.NewUnaryHandler(
		AuthAPILoginWithEmailProcedure,
		svc.LoginWithEmail,
		connect.WithSchema(authAPIMethods.ByName("LoginWithEmail")),
		connect.WithHandlerOptions(opts...),
	)
	authAPILoginWithCodeHandler := connect.NewUnaryHandler(
		AuthAPILoginWithCodeProcedure,
		svc.LoginWithCode,
		connect.WithSchema(authAPIMethods.ByName("LoginWithCode")),
		connect.WithHandlerOptions(opts...),
	)
	authAPILogoutHandler := connect.NewUnaryHandler(
		AuthAPILogoutProcedure,
		svc.Logout,
		connect.WithSchema(authAPIMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	authAPIRefreshTokenHandler := connect.NewUnaryHandler(
		AuthAPIRefreshTokenProcedure,
		svc.RefreshToken,
		connect.WithSchema(authAPIMethods.ByName("RefreshToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/saas.v1.AuthAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthAPILoginWithEmailProcedure:
			authAPILoginWithEmailHandler.ServeHTTP(w, r)
		case AuthAPILoginWithCodeProcedure:
			authAPILoginWithCodeHandler.ServeHTTP(w, r)
		case AuthAPILogoutProcedure:
			authAPILogoutHandler.ServeHTTP(w, r)
		case AuthAPIRefreshTokenProcedure:
			authAPIRefreshTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthAPIHandler struct{}

func (UnimplementedAuthAPIHandler) LoginWithEmail(context.Context, *connect.Request[v1.LoginWithEmailRequest]) (*connect.Response[v1.LoginWithEmailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("saas.v1.AuthAPI.LoginWithEmail is not implemented"))
}

func (UnimplementedAuthAPIHandler) LoginWithCode(context.Context, *connect.Request[v1.LoginWithCodeRequest]) (*connect.Response[v1.LoginWithCodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("saas.v1.AuthAPI.LoginWithCode is not implemented"))
}

func (UnimplementedAuthAPIHandler) Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("saas.v1.AuthAPI.Logout is not implemented"))
}

func (UnimplementedAuthAPIHandler) RefreshToken(context.Context, *connect.Request[v1.RefreshTokenRequest]) (*connect.Response[v1.RefreshTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("saas.v1.AuthAPI.RefreshToken is not implemented"))
}
