// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: saas/v1/user.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/vtuanjs/saas_management/packages/go/buf/saas/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserAPIName is the fully-qualified name of the UserAPI service.
	UserAPIName = "saas.v1.UserAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserAPIRegisterProcedure is the fully-qualified name of the UserAPI's Register RPC.
	UserAPIRegisterProcedure = "/saas.v1.UserAPI/Register"
)

// UserAPIClient is a client for the saas.v1.UserAPI service.
type UserAPIClient interface {
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
}

// NewUserAPIClient constructs a client for the saas.v1.UserAPI service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userAPIMethods := v1.File_saas_v1_user_proto.Services().ByName("UserAPI").Methods()
	return &userAPIClient{
		register: connect.NewClient[v1.RegisterRequest, v1.RegisterResponse](
			httpClient,
			baseURL+UserAPIRegisterProcedure,
			connect.WithSchema(userAPIMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userAPIClient implements UserAPIClient.
type userAPIClient struct {
	register *connect.Client[v1.RegisterRequest, v1.RegisterResponse]
}

// Register calls saas.v1.UserAPI.Register.
func (c *userAPIClient) Register(ctx context.Context, req *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// UserAPIHandler is an implementation of the saas.v1.UserAPI service.
type UserAPIHandler interface {
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
}

// NewUserAPIHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserAPIHandler(svc UserAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userAPIMethods := v1.File_saas_v1_user_proto.Services().ByName("UserAPI").Methods()
	userAPIRegisterHandler := connect.NewUnaryHandler(
		UserAPIRegisterProcedure,
		svc.Register,
		connect.WithSchema(userAPIMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	return "/saas.v1.UserAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserAPIRegisterProcedure:
			userAPIRegisterHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedUserAPIHandler struct{}

func (UnimplementedUserAPIHandler) Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("saas.v1.UserAPI.Register is not implemented"))
}
