// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	GetUserByID(ctx context.Context, id string) (*User, error)
}

var _ Querier = (*Queries)(nil)
