// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: saas/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginWithEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithEmailRequest) Reset() {
	*x = LoginWithEmailRequest{}
	mi := &file_saas_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithEmailRequest) ProtoMessage() {}

func (x *LoginWithEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saas_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithEmailRequest.ProtoReflect.Descriptor instead.
func (*LoginWithEmailRequest) Descriptor() ([]byte, []int) {
	return file_saas_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginWithEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginWithEmailRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginWithEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithEmailResponse) Reset() {
	*x = LoginWithEmailResponse{}
	mi := &file_saas_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithEmailResponse) ProtoMessage() {}

func (x *LoginWithEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saas_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithEmailResponse.ProtoReflect.Descriptor instead.
func (*LoginWithEmailResponse) Descriptor() ([]byte, []int) {
	return file_saas_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginWithEmailResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginWithEmailResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginWithCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithCodeRequest) Reset() {
	*x = LoginWithCodeRequest{}
	mi := &file_saas_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithCodeRequest) ProtoMessage() {}

func (x *LoginWithCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saas_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithCodeRequest.ProtoReflect.Descriptor instead.
func (*LoginWithCodeRequest) Descriptor() ([]byte, []int) {
	return file_saas_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginWithCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LoginWithCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithCodeResponse) Reset() {
	*x = LoginWithCodeResponse{}
	mi := &file_saas_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithCodeResponse) ProtoMessage() {}

func (x *LoginWithCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saas_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithCodeResponse.ProtoReflect.Descriptor instead.
func (*LoginWithCodeResponse) Descriptor() ([]byte, []int) {
	return file_saas_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginWithCodeResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginWithCodeResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_saas_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saas_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_saas_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_saas_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saas_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_saas_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_saas_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saas_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_saas_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_saas_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saas_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_saas_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_saas_v1_auth_proto protoreflect.FileDescriptor

const file_saas_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12saas/v1/auth.proto\x12\asaas.v1\"I\n" +
	"\x15LoginWithEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"`\n" +
	"\x16LoginWithEmailResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"*\n" +
	"\x14LoginWithCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"_\n" +
	"\x15LoginWithCodeResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"(\n" +
	"\rLogoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"^\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken2\xb4\x02\n" +
	"\aAuthAPI\x12Q\n" +
	"\x0eLoginWithEmail\x12\x1e.saas.v1.LoginWithEmailRequest\x1a\x1f.saas.v1.LoginWithEmailResponse\x12N\n" +
	"\rLoginWithCode\x12\x1d.saas.v1.LoginWithCodeRequest\x1a\x1e.saas.v1.LoginWithCodeResponse\x129\n" +
	"\x06Logout\x12\x16.saas.v1.LogoutRequest\x1a\x17.saas.v1.LogoutResponse\x12K\n" +
	"\fRefreshToken\x12\x1c.saas.v1.RefreshTokenRequest\x1a\x1d.saas.v1.RefreshTokenResponseB\x91\x01\n" +
	"\vcom.saas.v1B\tAuthProtoP\x01Z:github.com/vtuanjs/saas_management/packages/go/buf/saas/v1\xa2\x02\x03SXX\xaa\x02\aSaas.V1\xca\x02\aSaas\\V1\xe2\x02\x13Saas\\V1\\GPBMetadata\xea\x02\bSaas::V1b\x06proto3"

var (
	file_saas_v1_auth_proto_rawDescOnce sync.Once
	file_saas_v1_auth_proto_rawDescData []byte
)

func file_saas_v1_auth_proto_rawDescGZIP() []byte {
	file_saas_v1_auth_proto_rawDescOnce.Do(func() {
		file_saas_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saas_v1_auth_proto_rawDesc), len(file_saas_v1_auth_proto_rawDesc)))
	})
	return file_saas_v1_auth_proto_rawDescData
}

var file_saas_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_saas_v1_auth_proto_goTypes = []any{
	(*LoginWithEmailRequest)(nil),  // 0: saas.v1.LoginWithEmailRequest
	(*LoginWithEmailResponse)(nil), // 1: saas.v1.LoginWithEmailResponse
	(*LoginWithCodeRequest)(nil),   // 2: saas.v1.LoginWithCodeRequest
	(*LoginWithCodeResponse)(nil),  // 3: saas.v1.LoginWithCodeResponse
	(*LogoutRequest)(nil),          // 4: saas.v1.LogoutRequest
	(*LogoutResponse)(nil),         // 5: saas.v1.LogoutResponse
	(*RefreshTokenRequest)(nil),    // 6: saas.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),   // 7: saas.v1.RefreshTokenResponse
}
var file_saas_v1_auth_proto_depIdxs = []int32{
	0, // 0: saas.v1.AuthAPI.LoginWithEmail:input_type -> saas.v1.LoginWithEmailRequest
	2, // 1: saas.v1.AuthAPI.LoginWithCode:input_type -> saas.v1.LoginWithCodeRequest
	4, // 2: saas.v1.AuthAPI.Logout:input_type -> saas.v1.LogoutRequest
	6, // 3: saas.v1.AuthAPI.RefreshToken:input_type -> saas.v1.RefreshTokenRequest
	1, // 4: saas.v1.AuthAPI.LoginWithEmail:output_type -> saas.v1.LoginWithEmailResponse
	3, // 5: saas.v1.AuthAPI.LoginWithCode:output_type -> saas.v1.LoginWithCodeResponse
	5, // 6: saas.v1.AuthAPI.Logout:output_type -> saas.v1.LogoutResponse
	7, // 7: saas.v1.AuthAPI.RefreshToken:output_type -> saas.v1.RefreshTokenResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_saas_v1_auth_proto_init() }
func file_saas_v1_auth_proto_init() {
	if File_saas_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saas_v1_auth_proto_rawDesc), len(file_saas_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saas_v1_auth_proto_goTypes,
		DependencyIndexes: file_saas_v1_auth_proto_depIdxs,
		MessageInfos:      file_saas_v1_auth_proto_msgTypes,
	}.Build()
	File_saas_v1_auth_proto = out.File
	file_saas_v1_auth_proto_goTypes = nil
	file_saas_v1_auth_proto_depIdxs = nil
}
