// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: saas/v1/entity.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachmentType int32

const (
	AttachmentType_ATTACHMENT_TYPE_UNSPECIFIED AttachmentType = 0
	AttachmentType_ATTACHMENT_TYPE_PDF         AttachmentType = 1
	AttachmentType_ATTACHMENT_TYPE_IMAGE       AttachmentType = 2
	AttachmentType_ATTACHMENT_TYPE_VIDEO       AttachmentType = 3
)

// Enum value maps for AttachmentType.
var (
	AttachmentType_name = map[int32]string{
		0: "ATTACHMENT_TYPE_UNSPECIFIED",
		1: "ATTACHMENT_TYPE_PDF",
		2: "ATTACHMENT_TYPE_IMAGE",
		3: "ATTACHMENT_TYPE_VIDEO",
	}
	AttachmentType_value = map[string]int32{
		"ATTACHMENT_TYPE_UNSPECIFIED": 0,
		"ATTACHMENT_TYPE_PDF":         1,
		"ATTACHMENT_TYPE_IMAGE":       2,
		"ATTACHMENT_TYPE_VIDEO":       3,
	}
)

func (x AttachmentType) Enum() *AttachmentType {
	p := new(AttachmentType)
	*p = x
	return p
}

func (x AttachmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttachmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_saas_v1_entity_proto_enumTypes[0].Descriptor()
}

func (AttachmentType) Type() protoreflect.EnumType {
	return &file_saas_v1_entity_proto_enumTypes[0]
}

func (x AttachmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttachmentType.Descriptor instead.
func (AttachmentType) EnumDescriptor() ([]byte, []int) {
	return file_saas_v1_entity_proto_rawDescGZIP(), []int{0}
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	FromInternal  bool                   `protobuf:"varint,3,opt,name=from_internal,json=fromInternal,proto3" json:"from_internal,omitempty"`
	Type          AttachmentType         `protobuf:"varint,4,opt,name=type,proto3,enum=saas.v1.AttachmentType" json:"type,omitempty"`
	Ref           string                 `protobuf:"bytes,5,opt,name=ref,proto3" json:"ref,omitempty"`
	ReturnUrl     string                 `protobuf:"bytes,6,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_saas_v1_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_saas_v1_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_saas_v1_entity_proto_rawDescGZIP(), []int{0}
}

func (x *Attachment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attachment) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Attachment) GetFromInternal() bool {
	if x != nil {
		return x.FromInternal
	}
	return false
}

func (x *Attachment) GetType() AttachmentType {
	if x != nil {
		return x.Type
	}
	return AttachmentType_ATTACHMENT_TYPE_UNSPECIFIED
}

func (x *Attachment) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Attachment) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        *Attachment            `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	LastLogin     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	Ref           string                 `protobuf:"bytes,9,opt,name=ref,proto3" json:"ref,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_saas_v1_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_saas_v1_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_saas_v1_entity_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAvatar() *Attachment {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_saas_v1_entity_proto protoreflect.FileDescriptor

const file_saas_v1_entity_proto_rawDesc = "" +
	"\n" +
	"\x14saas/v1/entity.proto\x12\asaas.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x01\n" +
	"\n" +
	"Attachment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12#\n" +
	"\rfrom_internal\x18\x03 \x01(\bR\ffromInternal\x12+\n" +
	"\x04type\x18\x04 \x01(\x0e2\x17.saas.v1.AttachmentTypeR\x04type\x12\x10\n" +
	"\x03ref\x18\x05 \x01(\tR\x03ref\x12\x1d\n" +
	"\n" +
	"return_url\x18\x06 \x01(\tR\treturnUrl\"\x82\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12+\n" +
	"\x06avatar\x18\a \x01(\v2\x13.saas.v1.AttachmentR\x06avatar\x129\n" +
	"\n" +
	"last_login\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x12\x10\n" +
	"\x03ref\x18\t \x01(\tR\x03ref\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\x80\x01\n" +
	"\x0eAttachmentType\x12\x1f\n" +
	"\x1bATTACHMENT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ATTACHMENT_TYPE_PDF\x10\x01\x12\x19\n" +
	"\x15ATTACHMENT_TYPE_IMAGE\x10\x02\x12\x19\n" +
	"\x15ATTACHMENT_TYPE_VIDEO\x10\x03B\x93\x01\n" +
	"\vcom.saas.v1B\vEntityProtoP\x01Z:github.com/vtuanjs/saas_management/packages/go/buf/saas/v1\xa2\x02\x03SXX\xaa\x02\aSaas.V1\xca\x02\aSaas\\V1\xe2\x02\x13Saas\\V1\\GPBMetadata\xea\x02\bSaas::V1b\x06proto3"

var (
	file_saas_v1_entity_proto_rawDescOnce sync.Once
	file_saas_v1_entity_proto_rawDescData []byte
)

func file_saas_v1_entity_proto_rawDescGZIP() []byte {
	file_saas_v1_entity_proto_rawDescOnce.Do(func() {
		file_saas_v1_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saas_v1_entity_proto_rawDesc), len(file_saas_v1_entity_proto_rawDesc)))
	})
	return file_saas_v1_entity_proto_rawDescData
}

var file_saas_v1_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_saas_v1_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_saas_v1_entity_proto_goTypes = []any{
	(AttachmentType)(0),           // 0: saas.v1.AttachmentType
	(*Attachment)(nil),            // 1: saas.v1.Attachment
	(*User)(nil),                  // 2: saas.v1.User
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_saas_v1_entity_proto_depIdxs = []int32{
	0, // 0: saas.v1.Attachment.type:type_name -> saas.v1.AttachmentType
	1, // 1: saas.v1.User.avatar:type_name -> saas.v1.Attachment
	3, // 2: saas.v1.User.last_login:type_name -> google.protobuf.Timestamp
	3, // 3: saas.v1.User.created_at:type_name -> google.protobuf.Timestamp
	3, // 4: saas.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_saas_v1_entity_proto_init() }
func file_saas_v1_entity_proto_init() {
	if File_saas_v1_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saas_v1_entity_proto_rawDesc), len(file_saas_v1_entity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_saas_v1_entity_proto_goTypes,
		DependencyIndexes: file_saas_v1_entity_proto_depIdxs,
		EnumInfos:         file_saas_v1_entity_proto_enumTypes,
		MessageInfos:      file_saas_v1_entity_proto_msgTypes,
	}.Build()
	File_saas_v1_entity_proto = out.File
	file_saas_v1_entity_proto_goTypes = nil
	file_saas_v1_entity_proto_depIdxs = nil
}
