// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: saas/v1/entity.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserSalutationType int32

const (
	UserSalutationType_USER_SALUTATION_TYPE_UNSPECIFIED UserSalutationType = 0
	UserSalutationType_USER_SALUTATION_TYPE_MR          UserSalutationType = 1
	UserSalutationType_USER_SALUTATION_TYPE_MRS         UserSalutationType = 2
	UserSalutationType_USER_SALUTATION_TYPE_MS          UserSalutationType = 3
)

// Enum value maps for UserSalutationType.
var (
	UserSalutationType_name = map[int32]string{
		0: "USER_SALUTATION_TYPE_UNSPECIFIED",
		1: "USER_SALUTATION_TYPE_MR",
		2: "USER_SALUTATION_TYPE_MRS",
		3: "USER_SALUTATION_TYPE_MS",
	}
	UserSalutationType_value = map[string]int32{
		"USER_SALUTATION_TYPE_UNSPECIFIED": 0,
		"USER_SALUTATION_TYPE_MR":          1,
		"USER_SALUTATION_TYPE_MRS":         2,
		"USER_SALUTATION_TYPE_MS":          3,
	}
)

func (x UserSalutationType) Enum() *UserSalutationType {
	p := new(UserSalutationType)
	*p = x
	return p
}

func (x UserSalutationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserSalutationType) Descriptor() protoreflect.EnumDescriptor {
	return file_saas_v1_entity_proto_enumTypes[0].Descriptor()
}

func (UserSalutationType) Type() protoreflect.EnumType {
	return &file_saas_v1_entity_proto_enumTypes[0]
}

func (x UserSalutationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserSalutationType.Descriptor instead.
func (UserSalutationType) EnumDescriptor() ([]byte, []int) {
	return file_saas_v1_entity_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username             string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Salutation           UserSalutationType     `protobuf:"varint,4,opt,name=salutation,proto3,enum=saas.v1.UserSalutationType" json:"salutation,omitempty"`
	Phone                string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName            string                 `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string                 `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Name                 string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	AvatarId             string                 `protobuf:"bytes,9,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	LastLogin            *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	RefId                string                 `protobuf:"bytes,11,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	IsLocked             bool                   `protobuf:"varint,12,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	IsActivated          bool                   `protobuf:"varint,13,opt,name=is_activated,json=isActivated,proto3" json:"is_activated,omitempty"`
	IsAdmin              bool                   `protobuf:"varint,14,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsChangePassRequired bool                   `protobuf:"varint,15,opt,name=is_change_pass_required,json=isChangePassRequired,proto3" json:"is_change_pass_required,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_saas_v1_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_saas_v1_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_saas_v1_entity_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetSalutation() UserSalutationType {
	if x != nil {
		return x.Salutation
	}
	return UserSalutationType_USER_SALUTATION_TYPE_UNSPECIFIED
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *User) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *User) GetIsActivated() bool {
	if x != nil {
		return x.IsActivated
	}
	return false
}

func (x *User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *User) GetIsChangePassRequired() bool {
	if x != nil {
		return x.IsChangePassRequired
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_saas_v1_entity_proto protoreflect.FileDescriptor

const file_saas_v1_entity_proto_rawDesc = "" +
	"\n" +
	"\x14saas/v1/entity.proto\x12\asaas.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x05\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12;\n" +
	"\n" +
	"salutation\x18\x04 \x01(\x0e2\x1b.saas.v1.UserSalutationTypeR\n" +
	"salutation\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"first_name\x18\x06 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\a \x01(\tR\blastName\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x1b\n" +
	"\tavatar_id\x18\t \x01(\tR\bavatarId\x129\n" +
	"\n" +
	"last_login\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x12\x15\n" +
	"\x06ref_id\x18\v \x01(\tR\x05refId\x12\x1b\n" +
	"\tis_locked\x18\f \x01(\bR\bisLocked\x12!\n" +
	"\fis_activated\x18\r \x01(\bR\visActivated\x12\x19\n" +
	"\bis_admin\x18\x0e \x01(\bR\aisAdmin\x125\n" +
	"\x17is_change_pass_required\x18\x0f \x01(\bR\x14isChangePassRequired\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt*\x92\x01\n" +
	"\x12UserSalutationType\x12$\n" +
	" USER_SALUTATION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17USER_SALUTATION_TYPE_MR\x10\x01\x12\x1c\n" +
	"\x18USER_SALUTATION_TYPE_MRS\x10\x02\x12\x1b\n" +
	"\x17USER_SALUTATION_TYPE_MS\x10\x03B\x93\x01\n" +
	"\vcom.saas.v1B\vEntityProtoP\x01Z:github.com/vtuanjs/saas_management/packages/go/buf/saas/v1\xa2\x02\x03SXX\xaa\x02\aSaas.V1\xca\x02\aSaas\\V1\xe2\x02\x13Saas\\V1\\GPBMetadata\xea\x02\bSaas::V1b\x06proto3"

var (
	file_saas_v1_entity_proto_rawDescOnce sync.Once
	file_saas_v1_entity_proto_rawDescData []byte
)

func file_saas_v1_entity_proto_rawDescGZIP() []byte {
	file_saas_v1_entity_proto_rawDescOnce.Do(func() {
		file_saas_v1_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saas_v1_entity_proto_rawDesc), len(file_saas_v1_entity_proto_rawDesc)))
	})
	return file_saas_v1_entity_proto_rawDescData
}

var file_saas_v1_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_saas_v1_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_saas_v1_entity_proto_goTypes = []any{
	(UserSalutationType)(0),       // 0: saas.v1.UserSalutationType
	(*User)(nil),                  // 1: saas.v1.User
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_saas_v1_entity_proto_depIdxs = []int32{
	0, // 0: saas.v1.User.salutation:type_name -> saas.v1.UserSalutationType
	2, // 1: saas.v1.User.last_login:type_name -> google.protobuf.Timestamp
	2, // 2: saas.v1.User.created_at:type_name -> google.protobuf.Timestamp
	2, // 3: saas.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	2, // 4: saas.v1.User.deleted_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_saas_v1_entity_proto_init() }
func file_saas_v1_entity_proto_init() {
	if File_saas_v1_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saas_v1_entity_proto_rawDesc), len(file_saas_v1_entity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_saas_v1_entity_proto_goTypes,
		DependencyIndexes: file_saas_v1_entity_proto_depIdxs,
		EnumInfos:         file_saas_v1_entity_proto_enumTypes,
		MessageInfos:      file_saas_v1_entity_proto_msgTypes,
	}.Build()
	File_saas_v1_entity_proto = out.File
	file_saas_v1_entity_proto_goTypes = nil
	file_saas_v1_entity_proto_depIdxs = nil
}
