// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: saas/v1/user.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Salutation    UserSalutationType     `protobuf:"varint,3,opt,name=salutation,proto3,enum=saas.v1.UserSalutationType" json:"salutation,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_saas_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saas_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_saas_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetSalutation() UserSalutationType {
	if x != nil {
		return x.Salutation
	}
	return UserSalutationType_USER_SALUTATION_TYPE_UNSPECIFIED
}

func (x *RegisterRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_saas_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saas_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_saas_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_saas_v1_user_proto protoreflect.FileDescriptor

const file_saas_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12saas/v1/user.proto\x12\asaas.v1\x1a\x14saas/v1/entity.proto\"\xd0\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12;\n" +
	"\n" +
	"salutation\x18\x03 \x01(\x0e2\x1b.saas.v1.UserSalutationTypeR\n" +
	"salutation\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"5\n" +
	"\x10RegisterResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.saas.v1.UserR\x04user2L\n" +
	"\aUserAPI\x12A\n" +
	"\bRegister\x12\x18.saas.v1.RegisterRequest\x1a\x19.saas.v1.RegisterResponse\"\x00B\x91\x01\n" +
	"\vcom.saas.v1B\tUserProtoP\x01Z:github.com/vtuanjs/saas_management/packages/go/buf/saas/v1\xa2\x02\x03SXX\xaa\x02\aSaas.V1\xca\x02\aSaas\\V1\xe2\x02\x13Saas\\V1\\GPBMetadata\xea\x02\bSaas::V1b\x06proto3"

var (
	file_saas_v1_user_proto_rawDescOnce sync.Once
	file_saas_v1_user_proto_rawDescData []byte
)

func file_saas_v1_user_proto_rawDescGZIP() []byte {
	file_saas_v1_user_proto_rawDescOnce.Do(func() {
		file_saas_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saas_v1_user_proto_rawDesc), len(file_saas_v1_user_proto_rawDesc)))
	})
	return file_saas_v1_user_proto_rawDescData
}

var file_saas_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_saas_v1_user_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: saas.v1.RegisterRequest
	(*RegisterResponse)(nil), // 1: saas.v1.RegisterResponse
	(UserSalutationType)(0),  // 2: saas.v1.UserSalutationType
	(*User)(nil),             // 3: saas.v1.User
}
var file_saas_v1_user_proto_depIdxs = []int32{
	2, // 0: saas.v1.RegisterRequest.salutation:type_name -> saas.v1.UserSalutationType
	3, // 1: saas.v1.RegisterResponse.user:type_name -> saas.v1.User
	0, // 2: saas.v1.UserAPI.Register:input_type -> saas.v1.RegisterRequest
	1, // 3: saas.v1.UserAPI.Register:output_type -> saas.v1.RegisterResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_saas_v1_user_proto_init() }
func file_saas_v1_user_proto_init() {
	if File_saas_v1_user_proto != nil {
		return
	}
	file_saas_v1_entity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saas_v1_user_proto_rawDesc), len(file_saas_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saas_v1_user_proto_goTypes,
		DependencyIndexes: file_saas_v1_user_proto_depIdxs,
		MessageInfos:      file_saas_v1_user_proto_msgTypes,
	}.Build()
	File_saas_v1_user_proto = out.File
	file_saas_v1_user_proto_goTypes = nil
	file_saas_v1_user_proto_depIdxs = nil
}
